# Generated by Django 4.0 on 2021-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointless_text', models.TextField()),
                ('serial_number', models.TextField()),
                ('owners', models.ManyToManyField(null=True, to='vulnerable.login')),
            ],
        ),
    ]
