# Generated by Django 4.0 on 2021-12-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0003_alter_alarmsystem_serial_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlarmSystem',
        ),
    ]
