# Generated by Django 4.0 on 2021-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerable', '0004_delete_alarmsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
